version: '3.8'

services:
  app:
    build: .
    ports:
      - 80:80
    networks:
      ipvlan_net:
        ipv4_address: 192.168.0.147

networks:
  ipvlan_net:
    driver: ipvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
